#!/bin/sh
chown -R root:wheel /usr/bin/jalDaemon
chown -R root:wheel /Library/LaunchDaemons/com.linqj.jalDaemon.plist
/bin/launchctl unload /Library/LaunchDaemons/com.linqj.jalDaemon.plist
/bin/launchctl load /Library/LaunchDaemons/com.linqj.jalDaemon.plist